### ISSUE TITLE
not working in vercel

### ISSUE THREAD

**Issue by aliakbar8099** [badrap/bar-of-progress#15]
not working in vercel

**Comment by Parth909** [comment]
True. @aliakbar8099 use `nextjs-progressbar` instead of using this.
https://www.npmjs.com/package/nextjs-progressbar

**Comment by jviide** [comment]
Do you have an example repository or site that demonstrates the problem?

**Comment by jviide** [comment]
Copy-pasting here from [the other issue](https://github.com/badrap/bar-of-progress/issues/20#issuecomment-1204717991), maybe it's useful in this case:

One thing worth noting is the `delay` option described [here](https://github.com/badrap/bar-of-progress#customization). The option controls how many milliseconds the page is given time to load before the progress bar is shown. By default it's 80 milliseconds.

So, if the progress bar is visible for you in the dev mode, but not in the built app, the reason _might_ be because your built pages are loading so fast that the progress bar is not shown. You can try setting the delay value to 0, but please note that even then the bar won't be shown for "instant" page loads (e.g. pages from the browser cache or preloaded when the mouse cursor is hovered over a link).

**Comment by jviide** [comment]
Closing this due to age.
