### ISSUE TITLE
Not working when app is built.

### ISSUE THREAD

**Issue by Parth909** [badrap/bar-of-progress#20]
Using Nextjs version 11.1.2. 

After building the app the progress bar is not visible.

It is installed as a regular dependency not as a dev dependency

**Comment by jviide** [comment]
Do you have an example repository or site that demonstrates the problem?

**Comment by jviide** [comment]
One thing worth noting is the `delay` option described [here](https://github.com/badrap/bar-of-progress#customization). The option controls how many milliseconds the page is given time to load before the progress bar is shown. By default it's 80 milliseconds.

So, if the progress bar is visible for you in the dev mode, but not in your built app, the reason _might_ be because your built pages are loading so fast that the progress bar is not shown. You can try setting the delay value to 0, but please note that even then the bar won't be shown for "instant" page loads (e.g. pages from the browser cache or preloaded when the mouse cursor is hovered over a link).

**Comment by Parth909** [comment]
Yes, got it
